DROP TABLE dictionary;
CREATE TABLE dictionary ( id bigint NOT NULL, datacode varchar(255), dataname varchar(255), datatype varchar(255), datatypename varchar(255), displayorder int, parentcode varchar(255), PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE file_storage;
CREATE TABLE file_storage ( id bigint NOT NULL AUTO_INCREMENT, created_date datetime NOT NULL, file_name varchar(255) NOT NULL, file_size bigint NOT NULL, last_modified_date datetime NOT NULL, no varchar(255) NOT NULL, suffix_name varchar(255) NOT NULL, PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE holiday;
CREATE TABLE holiday ( id bigint NOT NULL AUTO_INCREMENT, cause varchar(255), endtime varchar(255), starttime varchar(255), timelength double, flowtype varchar(255), holidaytype varchar(255), flowtypename varchar(255), holidaytypename varchar(255), instcode varchar(255), instname varchar(255), usercode varchar(255), username varchar(255), PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE inst_info;
CREATE TABLE inst_info ( instcode varchar(255) NOT NULL, address varchar(255), city varchar(255), instflag varchar(255), instname varchar(255), opdate varchar(255), oprcode varchar(255), province varchar(255), telno varchar(255), pinstinfo_instcode varchar(255), cityname varchar(255), instclass varchar(255), instclassname varchar(255), instflagname varchar(255), provincename varchar(255), contactname varchar(255), contacttelno varchar(255), instsname varchar(255), PRIMARY KEY (instcode), INDEX FKs9xsy0ghpgf8tmas3rtvx2l57 (pinstinfo_instcode) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE meeting;
CREATE TABLE meeting ( id bigint NOT NULL AUTO_INCREMENT, endtime varchar(255), flowtype varchar(255), flowtypename varchar(255), instcode varchar(255), instname varchar(255), meetingtype varchar(255), meetingtypename varchar(255), starttime varchar(255), subject varchar(255), summary varchar(255), timelength double, usercode varchar(255), username varchar(255), fileid varchar(255), filename varchar(255), meetingroom varchar(255), PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE menu;
CREATE TABLE menu ( menucode varchar(255) NOT NULL, description varchar(255), disporder int, instclass varchar(255), instclassname varchar(255), isleaf varchar(255), isleafname varchar(255), menulevel int, menuname varchar(255), opdate varchar(255), opinstcode varchar(255), opinstname varchar(255), oprcode varchar(255), oprname varchar(255), url varchar(255), pmenuinfo_menucode varchar(255), PRIMARY KEY (menucode), INDEX FK2s7vuwr15va4spwicgno2r4x1 (pmenuinfo_menucode) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE note;
CREATE TABLE note ( id bigint NOT NULL AUTO_INCREMENT, instcode varchar(255), instname varchar(255), meetingid bigint NOT NULL, meetingname varchar(255), notes varchar(10000), updatetime varchar(255), usercode varchar(255), username varchar(255), notename varchar(255), PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE role;
CREATE TABLE role ( rolecode varchar(255) NOT NULL, description varchar(255), instclass varchar(255), instclassname varchar(255), opdate datetime, opinstcode varchar(255), opinstname varchar(255), oprcode varchar(255), oprname varchar(255), rolename varchar(255), PRIMARY KEY (rolecode) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE role_menus;
CREATE TABLE role_menus ( role_rolecode varchar(255) NOT NULL, menus_menucode varchar(255) NOT NULL, INDEX FKg7lncclxjkkwsf2wk795b2bnk (menus_menucode), INDEX FKav4s6evemhk3n4tsgxu3bwqke (role_rolecode) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE user;
CREATE TABLE user ( usercode varchar(255) NOT NULL, address varchar(255), certno varchar(255), certtype varchar(255), certtypename varchar(255), email varchar(255), instname varchar(255), mobilephone varchar(255), opdate varchar(255), oprcode varchar(255), password varchar(255), postcode varchar(255), qq varchar(255), rolename varchar(255), telno varchar(255), userflag varchar(255), userflagname varchar(255), username varchar(255), inst_instcode varchar(255), PRIMARY KEY (usercode), INDEX FKr4tl7gcxavov1h3cpfouf218o (inst_instcode) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE user_roles;
CREATE TABLE user_roles ( user_usercode varchar(255) NOT NULL, roles_rolecode varchar(255) NOT NULL, INDEX FK1ooj4xg0xbcnmglooow7qnuww (roles_rolecode), INDEX FKkrajdt7ruy1qjg7nben6bym4f (user_usercode) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE inst_info ADD CONSTRAINT FKs9xsy0ghpgf8tmas3rtvx2l57 FOREIGN KEY (pinstinfo_instcode) REFERENCES inst_info (instcode);
ALTER TABLE menu ADD CONSTRAINT FK2s7vuwr15va4spwicgno2r4x1 FOREIGN KEY (pmenuinfo_menucode) REFERENCES menu (menucode);
ALTER TABLE role_menus ADD CONSTRAINT FKav4s6evemhk3n4tsgxu3bwqke FOREIGN KEY (role_rolecode) REFERENCES role (rolecode) ;
ALTER TABLE role_menus ADD CONSTRAINT FKg7lncclxjkkwsf2wk795b2bnk FOREIGN KEY (menus_menucode) REFERENCES menu (menucode);
ALTER TABLE user ADD CONSTRAINT FKr4tl7gcxavov1h3cpfouf218o FOREIGN KEY (inst_instcode) REFERENCES inst_info (instcode);
ALTER TABLE user_roles ADD CONSTRAINT FK1ooj4xg0xbcnmglooow7qnuww FOREIGN KEY (roles_rolecode) REFERENCES role (rolecode) ;
ALTER TABLE user_roles ADD CONSTRAINT FKkrajdt7ruy1qjg7nben6bym4f FOREIGN KEY (user_usercode) REFERENCES user (usercode);
